#!/bin/sh
### BEGIN INIT INFO
# Provides:
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

dir="/opt/nifi/current/bin"
RUN_AS_USER=nifi

name=nifi

case "$1" in
    start)
    cd "$dir"
    su - $RUN_AS_USER -c "$dir/nifi.sh start"
    ;;
    stop)
    cd "$dir"
    su - $RUN_AS_USER -c "$dir/nifi.sh stop"
    ;;
    restart)
    su - $RUN_AS_USER -c "$dir/nifi.sh restart"
    ;;
    status)
    su - $RUN_AS_USER -c "$dir/nifi.sh status"
    ;;
    *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0