= Cloudera Docker Sandbox Deployment Guide
ifdef::env-github,env-browser[:outfilesuffix: .adoc]

== About
In some cases you may want to deploy a Cloudera sandbox in AWS for a team to perform a simple proof of concept or avoid system
resource usage on your local computer. Cloudera offers a Docker image that is simliar to the Cloudera sandbox that you would
 download and install to your laptop.

WARNING: Once you create the docker container called "cloudera" do not remove the container unless you intend to delete all of your work and start cleanly. There are instructions below on
how to start and stop an existing container to retain your data

If you don't know Docker and want help setting this up contact Jeremy Merrifield.

== Prerequisites
You need access to an AWS instance and permission to create an EC2 instance

== Installation

=== Step 1: Create an EC2 instance
For this document we will configure a CoreOS AMI which is optimized for running Docker images.

    . Choose an AMI for the region you will configure the EC2 instance in

    https://coreos.com/os/docs/latest/booting-on-ec2.html

    . Create the EC2 instance. You might want to add more disk space than the default 8GB

    . If you are on the Teradata VPN add the following to your security group using "All TCP" for each one. If you are not on VPN add your current IP address and choose "All TCP"

        136.179.11.144/29
        141.206.0.0/16
        153.64.0.0/15
        153.65.16.10/32

    . After starting up the instance Login to the EC2 instance

       $ ssh -i <private_key> core@<IP_ADDRESS>

=== Step 2: Create Script to Start Docker Container
Create a shell script to startup the Docker container. This makes it easier to create a new container if you decided to delete it at some point and start clean.

    . vi startCloudera.sh

    . Add the following

    #!/bin/bash
    docker run --name cloudera \
    		--hostname=quickstart.cloudera \
    		--privileged=true -t -d \
    		-p 8888:8888 \
    		-p 7180:7180 \
    		-p 80:80 \
    		-p 7187:7187 \
    		-p 8079:8079 \
    		-p 8400:8400 \
    		-p 8161:8161 \
    		cloudera/quickstart:5.7.0-0-beta /usr/bin/docker-quickstart

    . Change permissions

    $ chmod 744 startCloudera.sh

    . Start the Container

    It will have to first download the Docker image which is about 4GB so give it some time

    $ ./startCloudera.sh

=== Step 3: Login to the Cloudera Container and Start Cloudera Manager

    . Login to the Docker container

    $ docker exec -it cloudera bash

    . Start Cloudera Manager

    $ /home/cloudera/cloudera-manager --express

    . Login to Cloudera Manager at <EC2_HOST>:7180 (username/password is cloudera/cloudera )

    . Start all services in Cloudera Manager

    . After it's started exit the container to go back to the CoreOS host

=== Step 4: Build a Cloudera Distribution of PCNG and Copy it to the Docker Container

 . Modify the pom.xml file for the thinkbig-services-app module. Change:

 <dependency> 
    <groupId>com.thinkbiganalytics.datalake</groupId> 
    <artifactId>thinkbig-service-monitor-ambari</artifactId> 
    <version>${project.version}</version> 
  </dependency/>

  To

   <dependency> 
      <groupId>com.thinkbiganalytics.datalake</groupId> 
      <artifactId>thinkbig-service-monitor-cloudera-service</artifactId> 
      <version>${project.version}</version> 
    </dependency/>

  . From the data-lake-accelerator root folder run

  $ mvn clean install -o -DskipTests

  . Copy the new RPM file to the CoreOS box

  $ scp -i ~/.ssh/<EC2_PRIVATE_KEY> <DLA_HOME>/install/target/rpm/thinkbig-datalake-accelerator/RPMS/noarch/thinkbig-datalake-accelerator core@<EC2_IP_ADDRESS>:/home/core

  . From the CoreOS host copy the RPM file to the Docker container

  $ docker cp /home/core/thinkbig-datalake-accelerator-<VERSION>.noarch.rpm cloudera:/tmp

=== Step 5: Install PCNG in the Docker Container

  . Login to the cloudera Docker container

  $ docker exec -it cloudera bash

  $ cd /tmp

  . Create Linux Users and Groups

  Creation of users and groups is done manually because many organizations have their own user and group
  management system. Therefore we cannot script it as part of the RPM install.

      $ useradd -r -m -s /bin/bash nifi
      $ useradd -r -m -s /bin/bash thinkbig
      $ useradd -r -m -s /bin/bash  activemq

      Validate the above commands created a group as well by looking at /etc/group. Some operating systems
      may not create them by default.

      $ cat /etc/group

      If the groups are missing then run the following

      $ groupadd thinkbig
      $ groupadd nifi
      $ groupadd activemq

  . Follow the instructions in the Deployment Wizard guide to install the RPM and other components

  NOTE: There is an issue installing the database script so say No to the wizard step asking to install the database script. We will do that manually. I will update this section when it's fixed.

  . Follow these steps that are not in the wizard deployment guide but are required to run PCNG in this environment

  .. Run the database scripts

    $ /opt/thinkbig/setup/sql/mysql/setup-mysql.sh root cloudera

  .. Edit /opt/thinkbig/thinkbig-services/conf/application.properties

  Make the following changes in addition to the Cloudera specific changes described in the Appendix section of the wizard deployment guide for Cloudera

  ###Ambari Services Check
  #ambariRestClientConfig.username=admin
  #ambariRestClientConfig.password=admin
  #ambariRestClientConfig.serverUrl=http://127.0.0.1:8080/api/v1
  #ambari.services.status=HDFS,HIVE,MAPREDUCE2,SQOOP

  ###Cloudera Services Check
  clouderaRestClientConfig.username=cloudera
  clouderaRestClientConfig.password=cloudera
  clouderaRestClientConfig.serverUrl=127.0.0.1
  cloudera.services.status=HDFS/[DATANODE,NAMENODE],HIVE/[HIVEMETASTORE,HIVESERVER2],YARN
  ##HDFS/[DATANODE,NAMENODE,SECONDARYNAMENODE],HIVE/[HIVEMETASTORE,HIVESERVER2],YARN,SQOOP

  .. Add the "thinkbig" user to the supergroup

  $ usermod -a -G supergroup thinkbig

  .. Run the following commands to address an issue with the Cloudera Sandbox and fix permissions.

  $ su - hdfs 
  $ hdfs dfs -chmod 775 /

  . Start up the Think Big Apps

  $ /opt/thinkbig/start-thinkbig-apps.sh

  . Try logging into <EC2_HOST>:8400 and <EC2_HOST>:8079

=== Shutting down the container when not in use
EC2 instance can get expensive to run. If you don't plan to use the sandbox for a period of time we recommend shutting down the EC2 instance. Here are instructions on
how to safely shut down the Cloudera sandbox and CoreOS host.

. Login to Cloudera Manager and tell it to stop all services

. On the CoreOS host type "docker stop cloudera"

. Shutdown the EC2 Instance

=== Starting up an Existing EC2 instance and Cloudera Docker Container

. Start the EC2 instance

. Login to the CoreOS host

. Type "docker start cloudera" to start the container

. SSH into the docker container

 $ docker exec -it cloudera bash

. Start Cloudera Manager

 $ /home/cloudera/cloudera-manager --express

. Login to Cloudera Manager and start all services



