CREATE INDEX NN_EXEC_PARAMS_STRING_VAL ON BATCH_JOB_EXECUTION_PARAMS (KEY_NAME,STRING_VAL);
CREATE INDEX NN_BATCH_JOB_EXEC_STATUS ON BATCH_JOB_EXECUTION (STATUS);
CREATE INDEX NN_BATCH_JOB_EXEC_EXIT_CODE ON BATCH_JOB_EXECUTION (EXIT_CODE(20));
CREATE INDEX NN_BATCH_JOB_EXEC_CREATE_TIME ON BATCH_JOB_EXECUTION (CREATE_TIME);
