import 'angular';
import './module-name';
import "./OverviewController";
import "./alerts/AlertsDirective";
import "./data-confidence-indicator/DataConfidenceIndicatorDirective";
import "./feed-health/FeedHealthTableCardDirective";
import "./feed-status-indicator/FeedsStatusIndicatorDirective";
import "./job-status-indicator/JobStatusIndicatorDirective";
import "./services-indicator/ServicesIndicatorDirective";