use thinkbig;
ALTER DATABASE thinkbig CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE BATCH_JOB_EXECUTION_CONTEXT MODIFY SERIALIZED_CONTEXT LONGTEXT;
ALTER TABLE BATCH_STEP_EXECUTION_CONTEXT MODIFY SERIALIZED_CONTEXT LONGTEXT;
ALTER TABLE BATCH_JOB_INSTANCE CHANGE COLUMN `JOB_NAME` `JOB_NAME` VARCHAR(255) NOT NULL;