import * as angular from 'angular';
import {moduleName} from './module-name';
import 'jquery';
import './AccessControlService';
import './StateService';
import './SearchService';
import './broadcast-service';
import './CommonRestUrlService';
import './PaginationDataService';
import './SideNavService';
import './TableOptionsService';
import './ConfigurationService';
import './AddButtonService';
import './FileUploadService';
import './WindowUnloadService';
import './Utils';
import './HttpService';
import './notification.service';
import './AngularHttpInterceptor';
import './UserGroupService';
import './AngularModuleExtensionService';
import './BroadcastConstants';
export  let moduleRequire = angular.module(moduleName);