import * as angular from 'angular';
import {moduleName} from './module-name';
import 'jquery';
import './AccessControlService';
import './StateService';
import './SearchService';
import './broadcast-service';
import './CommonRestUrlService';
//import './PaginationDataService';
import './SideNavService';
import './TableOptionsService';
//import './tab.service';
import './ConfigurationService';
import './AddButtonService';
import './FileUploadService';
import './WindowUnloadService';
import './preview-dataset-collection.service'
import './Utils';
import './HttpService';
import './notification.service';
import './AngularHttpInterceptor';
import './UserGroupService';
import './AngularModuleExtensionService';
import './BroadcastConstants';
import '../repository/services/template.service';
import './LoginNotificationService';
import {FileUpload} from "./FileUploadService";