use thinkbig;
delimiter //

create procedure remove_old_schema_040()

begin

DROP TABLE IF EXISTS CHANGE_SET_FILES_PATH;
DROP TABLE IF EXISTS CHANGE_SET_HIVE_TABLE_PART_VALUE;
DROP TABLE IF EXISTS CHANGE_SET_HIVE_TABLE;

DROP TABLE IF EXISTS CHANGE_SET_FILES;
DROP TABLE IF EXISTS DATA_OPERATION;
DROP TABLE IF EXISTS CHANGE_SET;
DROP TABLE IF EXISTS DATASET;


DROP TABLE IF EXISTS FEED_DESTINATION;
DROP TABLE IF EXISTS FEED_SOURCE;
DROP TABLE IF EXISTS DATASOURCE;

DROP TABLE IF EXISTS FEED_PROPERTIES;
DROP TABLE IF EXISTS FM_TEMPLATE;
DROP TABLE IF EXISTS CATEGORY;
DROP TABLE IF EXISTS FM_FEED;

IF EXISTS(SELECT table_name
            FROM INFORMATION_SCHEMA.COLUMNS
           WHERE table_schema = 'thinkbig'
             AND table_name LIKE 'FEED' and COLUMN_NAME = 'category_id')

-- If exists
THEN
ALTER TABLE`thinkbig`.`FEED`
DROP FOREIGN KEY `FKi6tlfq6nytlrb8429acoovlay`;
ALTER TABLE `thinkbig`.`FEED`
DROP COLUMN `category_id`,
DROP COLUMN `version`,
DROP COLUMN `sla_id`,
DROP COLUMN `state`,
DROP COLUMN `initialized`,
DROP COLUMN `display_name`,
DROP INDEX `FKi6tlfq6nytlrb8429acoovlay` ,
DROP INDEX `UK_j4px0sd8c2k3ycpw6uvqpl1c6` ;
END IF;


DROP TABLE IF EXISTS FM_CATEGORY;
DROP TABLE IF EXISTS SLA_METRIC;
DROP TABLE IF EXISTS SLA_OBLIGATION_GROUP;
DROP TABLE IF EXISTS SLA_OBLIGATION;
DROP TABLE IF EXISTS SLA;
END//

delimiter ;

-- Execute the procedure
call remove_old_schema_040();

-- Drop the procedure
drop procedure remove_old_schema_040;