import * as angular from 'angular';
import AlertsServiceV2 from "./services/AlertsServiceV2";
import EventService from "./services/EventService";
import OpsManagerFeedService from "./services/OpsManagerFeedService";
import ChartJobStatusService from "./services/ChartJobStatusService";
import IconService from "./services/IconStatusService";
import Nvd3ChartService from "./services/Nvd3ChartService";
import OpsManagerJobService from "./services/OpsManagerJobService";
import OpsManagerRestUrlService from "./services/OpsManagerRestUrlService";
import ProvenanceEventStatsService from "./services/ProvenanceEventStatsService";
import ServicesStatusData from "./services/ServicesStatusService";
import TabService from "./services/TabService";
import OpsManagerDashboardService from "./services/OpsManagerDashboardService";