
CREATE DATABASE if not exists thinkbig;
USE thinkbig;

CREATE TABLE NIFI_PIPELINE_CONTROLLER_STEP  (
  EVENT_ID BIGINT NOT NULL PRIMARY KEY,
     NIFI_EVENT_ID BIGINT,
     COMPONENT_ID VARCHAR(255),
 JOB_EXECUTION_ID BIGINT,
 STEP_EXECUTION_ID BIGINT
 ) ENGINE=InnoDB;


     CREATE TABLE NIFI_PIPELINE_CONTROLLER_JOB  (
     EVENT_ID BIGINT NOT NULL PRIMARY KEY,
     NIFI_EVENT_ID BIGINT,
     FLOW_FILE_UUID VARCHAR(255),
     FEED_ID BIGINT,
     FEED_NAME VARCHAR(255),
     JOB_INSTANCE_ID BIGINT,
     JOB_EXECUTION_ID BIGINT
     ) ENGINE=InnoDB;
