
CREATE DATABASE thinkbig_nifi;

CREATE TABLE NIFI_PROVENANCE_EVENT_SEQ (
	ID BIGINT NOT NULL,
	UNIQUE_KEY CHAR(1) NOT NULL,
	constraint UNIQUE_KEY_UN unique (UNIQUE_KEY)
) ENGINE=InnoDB;
INSERT INTO NIFI_PROVENANCE_EVENT_SEQ (ID, UNIQUE_KEY) select * from (select 0 as ID, '0' as UNIQUE_KEY) as tmp where not exists(select * from NIFI_PROVENANCE_EVENT_SEQ);


 CREATE TABLE NIFI_PROVENANCE_EVENT  (
    EVENT_ID BIGINT NOT NULL PRIMARY KEY,
	NIFI_EVENT_ID BIGINT  NOT NULL,
	EVENT_TYPE VARCHAR(50),
	FLOW_FILE_UUID VARCHAR(255),
	FLOW_FILE_ENTRY_DATE BIGINT,
	EVENT_TIME BIGINT,
	EVENT_DURATION BIGINT,
	LINEAGE_START_DATE BIGINT,
	COMPONENT_ID VARCHAR(255),
	COMPONENT_TYPE VARCHAR(255),
	PARENT_UUIDS VARCHAR(255),
	CHILD_UUIDS VARCHAR(255),
	DETAILS VARCHAR(255),
	ATTRIBUTES_JSON TEXT,
	JSON TEXT
) ENGINE=InnoDB;


CREATE TABLE NIFI_PIPELINE_CONTROLLER_STEP  (
  EVENT_ID BIGINT NOT NULL PRIMARY KEY,
     NIFI_EVENT_ID BIGINT,
     COMPONENT_ID VARCHAR(255),
 JOB_EXECUTION_ID BIGINT,
 STEP_EXECUTION_ID BIGINT
 ) ENGINE=InnoDB;


     CREATE TABLE NIFI_PIPELINE_CONTROLLER_JOB  (
     EVENT_ID BIGINT NOT NULL PRIMARY KEY,
     NIFI_EVENT_ID BIGINT,
     FLOW_FILE_UUID VARCHAR(255),
     FEED_ID BIGINT,
     FEED_NAME VARCHAR(255),
     JOB_INSTANCE_ID BIGINT,
     JOB_EXECUTION_ID BIGINT
     ) ENGINE=InnoDB;

