CREATE TABLE `NIFI_EVENT_SUMMARY_STATS` (
  `FM_FEED_NAME` varchar(45) NOT NULL,
  `NIFI_PROCESSOR_ID` varchar(45) NOT NULL,
  `NIFI_FEED_PROCESS_GROUP_ID` varchar(45) DEFAULT NULL,
  `COLLECTION_TIME` timestamp NULL DEFAULT NULL,
  `TOTAL_EVENTS` int(11) DEFAULT NULL,
  `DURATION_MILLIS` bigint(19) DEFAULT NULL,
  `BYTES_IN` bigint(19) DEFAULT NULL,
  `BYTES_OUT` bigint(19) DEFAULT NULL,
  `MIN_EVENT_TIME` timestamp NULL DEFAULT NULL,
  `MAX_EVENT_TIME` timestamp NULL DEFAULT NULL,
  `JOBS_STARTED` bigint(20) DEFAULT NULL,
  `JOBS_FINISHED` bigint(20) DEFAULT NULL,
  `PROCESSORS_FAILED` bigint(20) DEFAULT NULL,
  `FLOW_FILES_STARTED` bigint(20) DEFAULT NULL,
  `FLOW_FILES_FINISHED` bigint(20) DEFAULT NULL,
  `COLLECTION_ID` varchar(45) DEFAULT NULL,
  `COLLECTION_INTERVAL_SEC` bigint(20) DEFAULT NULL,
  `ID` varchar(45) NOT NULL,
  `PROCESSOR_NAME` varchar(255) DEFAULT NULL,
  `TOTAL_FINISHED_JOB_TIME` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;


ALTER TABLE `thinkbig`.`BATCH_NIFI_STEP`
ADD COLUMN `FLOW_FILE_ID` VARCHAR(45) NULL COMMENT '' AFTER `STEP_EXECUTION_ID`;