import * as angular from "angular";
import {moduleName} from "./module-name";
import "./ng-if-permission/ng-if-permission";
import "./card-layout/angular1";
import "./card-filter-header/angular1";
import "./custom-icons/custom-icons";
import "./view-type-selection/angular1";
import "./stepper/step-buttons";
import "./stepper/StepperService";
import "./stepper/stepper";
import "./file-upload/angular1";
import "./about-kylo/angular1";
import "./filters/filters";
import "./icon-picker-dialog/angular1";
import "./draggable/draggable";
import "./sticky/sticky";
import "./sticky-tabs/sticky-tabs";
import "./add-button/angular1";
import "./fixed-top-right/fixed-top-right";
import "./ui-router-breadcrumbs/angular1";
import "./kylo-options/angular1";
import "./vertical-section-layout/angular1";
import "./dir-pagination/dirPagination-arrows";
import "./browser-height/browser-height";
import "./options-menu/angular1";
import "./string-to-number/string-to-number";
import "./utils/IDGenerator";
import "./utils/StringUtils";
import "./utils/ArrayUtils";
import "./utils/DateTimeUtils";
// import "./accordion-menu/AccordionMenuService";
// import "./accordion-menu/accordion-menu";
// import "./accordion-menu/menu_toggle";
// import "./accordion-menu/menulink";
// import "./timer/kylo-timer";
import "./multiple-email-validator/multiple-email-validator.js";
import "./lazy-load-retain-order/lazy-load-retain-order";
import "./notifications/angular1";
import "jquery";

export const app = angular.module(moduleName);
