USE thinkbig;

DROP PROCEDURE IF EXISTS `abandon_feed_jobs`;

DELIMITER $$
CREATE PROCEDURE `abandon_feed_jobs`(in feed varchar(255))
BEGIN

UPDATE BATCH_JOB_EXECUTION
  INNER JOIN BATCH_JOB_INSTANCE ON BATCH_JOB_INSTANCE.JOB_INSTANCE_ID = BATCH_JOB_EXECUTION.JOB_INSTANCE_ID
SET BATCH_JOB_EXECUTION.STATUS = 'ABANDONED',
  BATCH_JOB_EXECUTION.EXIT_MESSAGE = CONCAT('Job manually abandoned @ ', DATE_FORMAT(now(), '%Y-%m-%d %T:%f'))
WHERE BATCH_JOB_INSTANCE.JOB_NAME = feed
  AND BATCH_JOB_EXECUTION.STATUS = 'FAILED';

END$$
DELIMITER ;
